<?php

namespace App\VitrineBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RecommandationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecommandationRepository extends EntityRepository
{
}
