#app_vitrine:
#    resource: "@AppVitrineBundle/Controller/"
#    type:     annotation
#    prefix:   /
    
app_vitrine:
    resource: "@AppVitrineBundle/Controller/"
    type:     annotation
    prefix:   /

root:
    pattern: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /home
        permanent: true

