parameters:
#    application_vitrine.example.class: Application\VitrineBundle\Example

services:
#    application_vitrine.example:
#        class: %application_vitrine.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
